### ISSUE TITLE
v1.0.0:'Click browser's refresh  button(F5)' brings users to root folder instead of remaining in the folder where action is triggered.

### ISSUE THREAD

**Issue by jkim485** [sciserver/scidrive-ui#11]
But clicking the refresh button on SciDrive UI keeps user in the folder where the action is triggered.

**Comment by jkim485** [comment]
tested on chrome 43.0.2357.130 m.

**Comment by raddick** [comment]
The desired action here is that a refresh should keep you in the same folder you were in before. Right?

In that case, this should definitely be a bug rather than an enhancement - but not a showstopper.

**Comment by jkim485** [comment]
The desired action here is that a refresh should keep you in the same folder you were in before. Right?
Yes.
