### ISSUE TITLE
v1.0.0:SD_WU_5: drag-and-drop selected folder from one panel to another doesn't work consistently

### ISSUE THREAD

**Issue by jkim485** [sciserver/scidrive-ui#15]
Moving folders from one to another into panel view doesn't work consistently. Also  file/folder list views do not get updated after moving folders one from another folders.

**Comment by jkim485** [comment]
tested on chrome 43.0.2357.130 m.

**Comment by raddick** [comment]
This could maybe be a showstopper, depending on how often it happens and in what contexts? The file drag-and-drop functionality is one of the main selling points of SciDrive.

**Comment by dimm0** [comment]
Fixed
