### ISSUE TITLE
v1.0.0:SD_WU_6: hangs when try to open the shared URL on Firefox

### ISSUE THREAD

**Issue by jkim485** [sciserver/scidrive-ui#16]

**Comment by dimm0** [comment]
Still an issue? Works for me

**Comment by dimm0** [comment]
Closing since no response

**Comment by jkim485** [comment]
Haven't tested on FireFox for a while.  I will check with Mike whether to support Firefox or not.

**Comment by dimm0** [comment]
This should work fine. I develop in firefox usually.
If it's broken, reopen the ticket with more info
