### ISSUE TITLE
v1.0.0:SD_WU_3:Create file doesn't work for 'Pull from URL' with 'Auto file name from URL' option 

### ISSUE THREAD

**Issue by jkim485** [sciserver/scidrive-ui#22]
if file name is given by user creating file with 'pull from url' does work.

**Comment by jkim485** [comment]
ps. 

if file name is given by user creating file with 'pull from url' does work.
but the folder view doesn't automatically refresh after file is created.

**Comment by jkim485** [comment]
Tested on scidrive 2: the issue has not been fixed.

A new bug is introduced for creating file with a pull from URL.
get an error message 'Error: undefined' even if the filename is given by user creating file with a pull from URL.

**Comment by dimm0** [comment]
Fixed

**Comment by jkim485** [comment]
Partly fixed.
1. Automatic filename extraction works for the following case:
https://www.pmmh.espci.fr/~jorge/ch4.pdf : extracted the filename is ch4.pdf
2. Automatic filename extraction does not work for the following case:
C:\codetest\test.xml- Get an error message "the value entered is not valid". But it is not clear how to fix the entered URL to make valid.

Would to be helpful for users what the valid URL syntax is.

**Comment by dimm0** [comment]
C:\codetest\test.xml- is not an URL at all...

**Comment by jkim485** [comment]
[jk reminder] test  with 

https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.115.153002#fulltext

**Comment by dimm0** [comment]
I can allow the "#" symbol in URLs, but this url also won't return any useful file...

**Comment by dimm0** [comment]
The "#" symbol in filename creates problems. Prohibiting for now, until fixed in service. Only regular filenames with letters and numbers are allowed.
