### ISSUE TITLE
Extracted metadata do not appear in MyDB

### ISSUE THREAD

**Issue by raddick** [sciserver/scidrive-ui#23]
I uploaded some files into SciDrive, right-clicked to extract metadata, and got an OK message. But the metadata did not appear in my CasJobs MyDB. I tried logging in and out of both sites - no luck.

Jai Won helped me set up the CasJobs/MyDB v2 metadata extractor, so this should have worked.

Screenshots below showing each stage of the process. Jai Won is experiencing exactly the same error.

It's possible that we are doing something wrong, in which case the test script needs to be updated, as well as the documentation on the site telling the user what to do.

But if this really is not working, then this is a real showstopper bug. Potential users are already asking why they should use SciDrive instead of Dropbox, and we're telling them "because SciDrive extracts your file metadata and stores it in your MyDB." If that's not working, people won't use SciDrive. Marking this as a showstopper for now.

![scidrive_connection_1](https://cloud.githubusercontent.com/assets/1709156/8436620/90f6fc62-1f27-11e5-879a-5e549cee341f.png)

![scidrive_connection_2](https://cloud.githubusercontent.com/assets/1709156/8436621/93f189dc-1f27-11e5-8277-9f4588968d0f.png)

![scidrive_connection_3](https://cloud.githubusercontent.com/assets/1709156/8436623/979b1314-1f27-11e5-8382-c2ba9e27f4bb.png)

**Comment by jkim485** [comment]
I have tried two plugins:
CasJobs/MyDB: endpoint
CasJobs/MyDB v2: 
  endpoints: http://scitest02.pha.jhu.edu.org/CasJobs/RestApi & http://scitest02.pha.jhu.edu.org/CasJobs/

All three cases failed to create tables in CasJobs.

**Comment by jkim485** [comment]
Tested on scidrive 2: still doesn't work.

Related issue might be #28.

**Comment by jkim485** [comment]
I closed the issue by mistake...

**Comment by jkim485** [comment]
Tested with fits files, and worked. 
Tested with CSV files, and did not appear in MyDB of CasJobs: according to the scidrive log , the metadata extraction was a successful. But the CSV file does not appear on 'ExtrnResources' table.
Its columns do not appear on "ExtrnKeyValue'' table.

**Comment by jkim485** [comment]
Mitya enabled CSV file metadata extraction.
Jai Won tested with a simple CSV file and the feature worked including creating a table & and inserting rows in the table in  MyDB..
-

**Comment by jkim485** [comment]
Jai Won tested with 2 fits file including binary tables.
- FITS file metadata it extraction as well as creating tables and inserting rows of the fits binary tables in MyDB worked.
- But there was an issue with handling "infinity" value in fits binary table: in such case the extraction could create tables corresponding to fits binary table but failed to insert rows in the tables in MyDB.

**Comment by jkim485** [comment]
This is an issue for FITS table extractor. 

How much testing has been done for FITS table extractor?
Any test scripts exist?

**Comment by jkim485** [comment]
Mitya,

Let's not worry about to fix this problem since the bug was to a specific FITS file.
