### ISSUE TITLE
V1.0.1:  SD_WU_4, SD_WU_5:  Drag and Drop "Icon" Does not always Display 

### ISSUE THREAD

**Issue by jkim485** [sciserver/scidrive-ui#26]
When dragging and dropping a file from one folder to another folder, the operation only works if the "green icon" appears when the file is selected for moving.  
However, to select a file require a two step selection: (a) click the file (b) then select and hold down the mouse to drag.
If you only select and hold down the mouse before the file is highlighted, the drag operation does not happen (and the green icon does not appear).

The current solution is always to select the file(s) first, then do the drag.

The required fix is to ensure that the file is 'selected' on the mouse down operation of the "drag", so that the drag operation kicks in. 

We have reported a few issues with dragging files, see also #15 and #14 .

**Comment by jkim485** [comment]
Tested on scidrive 2:

moving ANY file from one folder to another in a split view in scidrive: cannot move the selected files at all
- Followed the steps described above: after the green icon appeared when selected file(s), and dragged the selected files and release them in the second panel. But the drag operation didn't work.

**Comment by dimm0** [comment]
> If you only select and hold down the mouse before the file is highlighted, the drag operation does not happen (and the green icon does not appear).

If drag is performed on non-selected file, the selection happens. That's the way to select multiple files - to drag across them. There is no way to figure if user wants to drag a single file or select multiple files, the actions would be the same.

**Comment by jkim485** [comment]
It would be good to describe how to move files in the help page.

**Comment by dimm0** [comment]
Done
