### ISSUE TITLE
Directory address bar breaks when trying to display too many nested directories/long directory names

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/scidrive-ui#31]
After creating many directory levels (directories inside directories), the directory address bar reaches the end of the line and breaks, i.e., can't continue navigating to the following nested directory since it doesn't show. Furthermore, the server name is displaced downwards and is placed now overlaying the panel that displays the directory content. This panel does not show neither files nor directories it might contain.

**Comment by jkim485** [comment]
How many directory levels need to create the this issue?
Could you please attach an image showing the bug?

**Comment by mtaghiza** [comment]
just a few directories but with very long names are enough to break it.

**Comment by jkim485** [comment]
Could you please make a screen shot of the example and create an image file and upload it here? That would help!

**Comment by mtaghiza** [comment]
For example:

![untitled](https://cloud.githubusercontent.com/assets/12413605/8551403/5565af9a-24a4-11e5-9313-b85095452f9a.png)

**Comment by jkim485** [comment]
Mike suggests that

 if the char length of folder list > Max_list,  replace the root folder names with '...' and display only the names of the leaf level folders within Max_list.

**Comment by jkim485** [comment]
Tested on scidrive 2: the issue has not been fixed.

**Comment by dimm0** [comment]
For now the path will go under another element. Still possible to return to higher folder if one is visible.
