### ISSUE TITLE
Enhancement: add address bar for second panel.

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/scidrive-ui#33]
When the second panel is displayed, it does not show an address bar. We could add one as an enhancement.

**Comment by jkim485** [comment]
In particular if the second panel displays an empty folder there is no way to figure it out which folder it is.

**Comment by dimm0** [comment]
Second address bar will break current design. Fixed by making path change when mouse cursor is entering a panel - now it always shows the path of panel under the cursor.

**Comment by dimm0** [comment]
Actually, that makes it harder to choose a folder for second column, as cursor usually goes on top of the first column... Ideas are appreciated

**Comment by jkim485** [comment]
I don't have good idea. I have tried the solution you mentioned above( Fixed by making path change when mouse cursor is entering a panel - now it always shows the path of panel under the cursor.). 

But I haven't seen the path.

**Comment by dimm0** [comment]
Made the header of inactive panel greyed out, so that it's visible which panel is active and which path is shown. That seems like the best solution for now

**Comment by jkim485** [comment]
Sounds good.

Where is the active path shown? On the panel itself or on the address bar?

**Comment by dimm0** [comment]
It is available
Path is shown as before
