### ISSUE TITLE
Change "San Diego Super Computing Center UCSD" to "JHU" in browser tab description

### ISSUE THREAD

**Issue by mtaghiza** [sciserver/scidrive-ui#37]
When opening the new Scidrive-ui (or "Scidrive2"), the browser tab shows  "SciDrive of San Diego Super Computing Center UCSD". Probably want to change it to "SciDrive of Johns Hopkins University"

**Comment by jkim485** [comment]
Tested and not fixed.

**Comment by dimm0** [comment]
Fixed
