### ISSUE TITLE
v1.0.0:SD_WU_4: tested on scidrive 2: moving files from one folder to another in split view doesn't work

### ISSUE THREAD

**Issue by jkim485** [sciserver/scidrive-ui#39]
moving  ANY file from one folder to another in a split view in scidrive: cannot move the selected files at all. (related to issue #35)

**Comment by dmedv** [comment]
Jai Won and I tested this together. Moving files does work, but you need to click the refresh button to see the changes. There might be another problem with moving files between the panels (when files are selected in both panels). Needs more testing.

**Comment by jkim485** [comment]
Coping Jai Won's email about this issue:
Just tested moving files from one folder to another using second panel and it doesn’t work after refreshing. Even though it worked when we tested together a few minutes ago.
(tested on both Chrome and firefox)
What does work for sure is moving files from explorer to scidrive.


Mitya's reply:
I tested in both Chrome and Firefox, I think...
This bug could also be related to the database issue I mentioned. You could try to create a brand new user, that should solve the DB problem, it's only an issue with old users, I think.

**Comment by dimm0** [comment]
Should work now. Need to fix race condition - can create two files sometimes

**Comment by jkim485** [comment]
Tested and confirmed fix.

**Comment by jkim485** [comment]
Tested again and does not work.

**Comment by dmedv** [comment]
It does work for me...

**Comment by jkim485** [comment]
Tested again, and confirmed is not fixed.

**Comment by dimm0** [comment]
Fixed a bug, plz test
