### ISSUE TITLE
v1.0.0 Error message Passwords do not match. appear before entering repeat password

### ISSUE THREAD

**Issue by jkim485** [sciserver/scidrive-ui#4]
create user: 
1. enter password first time from register form.
2. get the following error message before start repeating password on the next field
"Error: Passwords do not match."

It might be better if the error message appears once a user finishes entering text on the repeat password field and click register.

**Comment by dimm0** [comment]
@raddick @jkim485 Can we move all user registration related tickets to where is belongs? That's not about scidrive-ui...
