### ISSUE TITLE
v1.0.0 can register more than once with a single email address

### ISSUE THREAD

**Issue by jkim485** [sciserver/scidrive-ui#5]
Should this be allowed?

**Comment by raddick** [comment]
This is really a question about the portal. Leaving it open here for now until we're ready to test Mitya's new portal.

**Comment by thakar** [comment]
Yeah it would make testing the portal very hard indeed if you couldn't
reuse emails (of course, it probably has no way of checking validity of
email addresses so you could use fake ones).

I thought casjobs did in fact enforce unique emails but clearly it must not
any more.

   Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
We are all atheists about most of the gods that societies have ever
believed in. Some of us just go one god further. [Richard Dawkins]

**Comment by raddick** [comment]
The current production CasJobs does indeed enforce unique emails. I just tried creating a new account with my current email, and got an error saying "Cannot create account; this email already exists."

Forget about testing - what about our end users? Do we want to allow multiple registrations on the same email address?

I don't think that allowing multiple registrations on an email hurts the user, but it does mean that we can't use email as the primary key in the users table.

Thoughts?

**Comment by thakar** [comment]
We don't use email as PK anyway AFAIK, probably webservicesid or userid.
However, we do need to continue to enforce email uniqueness in general, to
discourage people from creating multiple accounts just to get more space,
or when they forget their credentials.

   Ani

--
Aniruddha R. Thakar, Principal Research Scientist
Center for Astrophysical Sciences and
Institute for Data Intensive Engineering & Science (IDIES), JHU
3701 San Martin Drive, Baltimore MD 21218-2695
410-516-4850, thakar@jhu.edu,  www.sdss.jhu.edu/~thakar
<http://www.sdss.jhu.edu/%7Ethakar>
--------------------------------------------------------------------------------------
Whoever heard of a hundred thousand animals rushing together to
butcher each other, as men do everywhere (during war)?
[Desiderius Erasmus]

**Comment by jkim485** [comment]
I haven't seen a case using email address as PK. Agreed with Ani on enforcing email uniqueness .

**Comment by raddick** [comment]
OK, sounds like we've decided that we do want to enforce email uniqueness. Should we close this issue, then?

**Comment by raddick** [comment]
Oh, but the issue said that the user *can* register with more than one email address. That's not the behavior we want.

So this is no longer a question, but a bug. Changing labels accordingly.

**Comment by jkim485** [comment]
I think that this issue should be moved to single sign-on login portal.

@mikear69 
please confirm it and close it.
