### ISSUE TITLE
Should get space allocated - not clear to a new user whether space is allocated or not

### ISSUE THREAD

**Issue by jkim485** [sciserver/scidrive-ui#7]
Created two new users one from chrome, the other from Internet Explorer.
1.login with new username password.(abc1/abc1, abc2/abc2)
2.The web browser displays "this is a home everybody can access this page." only.

**Comment by dimm0** [comment]
Not a part of scidrive-ui

**Comment by dimm0** [comment]
Space is allocated automatically for any registered user

**Comment by jkim485** [comment]
This should be explained in the help page including how much space is allocated to each user.
